### PR TITLE
Issue 20: Connect Characteristics dropdown to SelectCharacteristic()

### PR DESCRIPTION
**Pull request by ehauner**
- hook up characteristics dropdown to Demo.SelectCharacteristic()

This is a fix for #20 

I don't have much experience with Unity projects and git. Please let me know if I should remove any of these files from the commit. Part of the change includes changing the Unity version, and I think that required the addition of some files.

### CODE REVIEW

**Comment by adabru** [comment]
Thanks @ehauner for the pull request! I guess the relevant lines are 3542-3554 in Demo.unity . Could you try to exclude the version change from the commit? E.g. by committing once after import, once after doing the change and then cherrypicking the change onto master? I'm not feeling very good when changing the version.

Btw instead of reopening the pull request you can also force push :+1:

**Comment by ehauner** [comment]
Yes. To be safe, I'll get a matching version of Unity then make the change. I didn't feel great about changing the version either.

**Comment by ehauner** [comment]
Updated and tested

**Comment by adabru** [comment]
Great!

**Pull request merged**
